# Generated by Django 4.2.1 on 2023-06-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='car_id',
            new_name='cart_id',
        ),
    ]
